theme="hurock"
baseurl = "https://leovergara1.github.io/Actual/"
languageCode = "en-us"
title = "Leos Vergara"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "leovergara11" 
copyright  = "Â© 2015 Copyright Text"
[author]
  name = ""
  email = ""
  
  github = "LeoVergara1"
  twitter = "Leovergara2"
  facebook = ""
  googleplus = ""
  linkedin = ""
  gaID = "Google Analytics Tracking ID"

[params]
  Description = ""
  # Optional
  disqusShortname = ""
  highlight_theme = "tomorrow-night"
  notoc = true


# Optional sections:
[permalinks]
  posts = "/:year/:month/:filename/"

[blackfriday]
  plainIdAnchors = true
